mykey = "clarusway"
ami = "ami-05576a079321f21f8"
region = "us-east-1"
instance_type = "t3a.medium"
nexus_server_secgr = "petclinic-nexus-server-secgr"
nexus-server-tag = "Nexus Server of Petclinic"
